name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:

      
    - uses: actions/checkout@v4
    - name: Change directory to /frontend/
      run: cd frontend
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: frontend
      run: npm ci
    - name: Install Playwright Browsers
      working-directory: frontend
      run: npx playwright install --with-deps
    # - name: Run react server
    #   working-directory: frontend
    #   run: npm run dev
    - uses: JarvusInnovations/background-action@v1
      name: Run React Dev Server - Background
      with:
        working-directory: frontend
        run: |
          npm ci
          npm run dev
        wait-on: |
          http://localhost:5173
        tail: true
        log-output-resume: stderr
        wait-for: 5m
        log-output: stderr,stdout
        log-output-if: failure

    - name: Run Playwright tests
      working-directory: frontend
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
